---
# tasks file for db_postgresql

# Обновление пакетного репозитория 
- name: Update list of packages
  apt:
    update_cache: yes
  become: yes
  tags:
    - db_postgresql_apt_update


# Установка пакетов
- name: Packet installing
  apt:
    name: "{{ item }}" 
    state: present
  loop:
    - "{{ packages_to_install }}"
  tags:
    - db_postgresql_install_packages 

# 
- name: "Start and enable services"
  service: 
    name=postgresql
    state=started 
    enabled=yes
  tags:
    - db_postgresql_start_enable_service


- name: Создание пользователя PRIMARY БД PostgreSQL
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    name: "{{ postgres_vars.db_user }}"
    password: "{{ postgres_vars.db_password }}"
    role_attr_flags: "{{ postgres_vars.attr | join(',') }}"
    state: present
  tags:
    - db_postgresql_create_postgres_user
  when: "'vm-6-primary-db' in inventory_hostname"












# - name: Create the databases
#   community.postgresql.postgresql_db:
#     name: "{{ postgres_vars.db_name  }}"
#     encoding: "UTF-8"
#   become: true
#   become_user: postgres
#   tags:
#     - db_postgresql_create_db




