---
# tasks file for db_postgresql

# =========================
# Блок с общими задачами
# =========================

# Обновление пакетного репозитория 
- name: Step 1 - Update list of packages
  apt:
    update_cache: yes
  become: true
  tags:
    - db_postgresql_apt_update

# Установка пакетов
- name: Step 2 - Packet installing
  apt:
    name: "{{ item }}" 
    state: present
  loop:
    - "{{ packages_to_install }}"
  tags:
    - db_postgresql_install_packages 

# Запуск сервиса и добавление в автозапуск
- name: Step 3 - Start and enable services
  service: 
    name=postgresql
    state=started 
    enabled=yes
  tags:
    - db_postgresql_start_enable_service

# Добавление секретных переменных
- name: Step 4 - Include secret variables
  include_vars: secrets.yml
  tags:
    - db_postgresql_add_secret_variables

# Создание динамических переменных
- name: Step 5 - Create dynamic variables
  set_fact:
    mount_point: "{{ hostvars[inventory_hostname]['external_disks'] | map(attribute='mount_point') | list }}"
  tags:
    - db_postgresql_create_dynamic_variables

# Создание группы безопасности
- name: Step 6 - Create a group for PostgreSQL access
  ansible.builtin.group:
    name: dbadmin
    state: present
  tags:
    - db_postgresql_create_Postgresql_group_access

# Добавление пользователей в группу безопасности
- name: Step 7 - Add multiple users to dbadmin group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: dbadmin
    append: yes
  loop:
    - postgres
    - sudo
    - "{{ postgres_wikiuser_user_vars.db_user }}"
  tags:
    - db_postgresql_add_users_dbadmin_group

# Смена владельцев директории
- name: Step 8 - Change group ownership for PostgreSQL directories
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: dbadmin
    state: directory
    recurse: true
  loop: 
  - "{{ mount_point }}"  # Указываем на директорию PostgreSQL
  - "/opt"  # Указываем на родительскую директорию
  tags:
    - db_postgresql_change_postgresql_path_ownership


# Установка разрешений для директории
- name: Step 9 - Set permissions for PostgreSQL directories
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ item }}"
    mode: '0770'  # Права для владельца и группы: чтение, запись, выполнение
    recurse: true
  # loop: "{{ mount_point }}"
  loop: 
    - "{{ mount_point }}"  # Указываем на директорию PostgreSQL
    - "/opt"  # Указываем на родительскую директорию
  tags:
    - db_postgresql_set_postgresql_permissions






