---
# vars file for db_postgresql
packages_to_install:
  - nginx
  - php 
  - php-intl
  - php-mbstring
  - php-xml
  - php-apcu 
  - php-curl
  - postgresql
  - postgresql-contrib
  - python3-psycopg2
  - acl

postgres_vars:
  db_user: wikiuser
  db_name: my_wiki
  db_password: your_password 
  attr: 
    - SUPERUSER
    - CREATEDB
    - CREATEROLE
    - LOGIN
    - INHERIT
  db_tablespace_name: primary_tablespace