---
# vars file for db_postgresql
apt_packages_to_install:
  - postgresql
  - postgresql-contrib
  - python3-psycopg2
  - acl
  - rsync
  - python3
  - python3-venv
  - python3-pip

pip3_packages_to_install:
  - pip>=24.3.1
  - python-dotenv
