---
# handlers file for zabbix_server_monitoring_system
- name: Postgresql Restarter
  ansible.builtin.service:
    name: zabbix-server
    state: restarted
    enabled: yes
  listen: "restart_zabbix_server"