# tasks file for mount_disk


# Инфо:
# 
# 1. Отобразить инфо о дисках и разделах: lsblk -f
# 2. Разметка диска новыми разделами (partition): fdisk /dev/<название устройства>
# 2.1. fdisk /dev/vdb далее g (создание таблицы разделов gpt) далее w (сохр. изменения и выйти)
# 3. Создание раздела диска (partition) и physical volume вместе с ним: fdisk /dev/<название устройства>
# 3.1. fdisk /dev/vdb далее n (создание раздела) далее 1 (номер раздела) далее enter (вопрос про секторы) далее w (сохр. изменения и выйти)
# 4. Инициализация Physical Volume: pvcreate /dev/<название раздела>
# 4.1. pvcreate /dev/vdb1 
# 5. Создание Volume Group: vgcreate <имя группы томов> /dev/<имя раздела>
# 5.1. vgcreate vg-db-storage /dev/vdb1 (vgs - проверка, что VG создан)
# 6. Cоздание Logical Volume: lvcreate -n <имя LV> -l <кол-во extents (можно посмотреть vgdisplay <имя VG>)> <имя VG>
# lvcreate -n lv-vhdd-1-monitoring-system-db -l 7167 vg-db-storage (lvs - проверка, что LV создан)
# 7. Форматирование LV и создание файловой системы ext4
# mkfs.ext4 /dev/vg-db-storage/lv-vhdd-1-monitoring-system-db
# 8. Создание точки монтирования
# mkdir /opt/vhdd-1-monitoring-system-db/
# 9. Монтирование LV
# mount /dev/vg-db-storage/lv-vhdd-1-monitoring-system-db /opt/vhdd-1-monitoring-system-db/
# 10. Добавить LV в автомонтирование /etc/fstab (проверка автомонтирования cat /etc/fstab или mount -a)
# echo "/dev/vg-db-storage/lv-vhdd-1-monitoring-system-db /opt/vhdd-1-monitoring-system-db/ ext4 defaults 0 0" | sudo tee -a /etc/fstab



---

- name: Шаг 1 - Получить disk_id и добавить "virtio-"
  set_fact:
    virtio_disk_ids: "{{ virtio_disk_ids | default([]) + ['virtio-' + item.disk_id] }}"
  loop: "{{ hostvars[inventory_hostname].external_disks | default([]) }}"

- name: Шаг 2 - Сравнить с ansible_facts.device_links.ids
  set_fact:
    device_names: "{{ device_names + [item.key] }}"
  loop: "{{ ansible_facts.device_links.ids | dict2items }}"
  when: item.value | intersect(virtio_disk_ids) | length > 0

- name: Шаг 3 - Создать динамические переменные
  set_fact:
    origin_path: "dev"
    device_path: "/{{ origin_path }}/{{ device_names | join(',') }}"
    volume_group: "vg-db-storage"  # Определение переменной для группы томов
    logical_volume: "lv-{{ hostvars[inventory_hostname]['external_disks'][0]['disk_name'] }}"  # Логический том
    physical_volume: "{{ device_path }}1"  # Физический том
    vg_lv_path: "/{{ origin_path }}/{{ volume_group }}/{{ logical_volume }}"
    file_system: "{{ hostvars[inventory_hostname]['external_disks'][0]['filesystem'] }}"  # Файловая система
    mount_point: "{{ hostvars[inventory_hostname]['external_disks'][0]['mount_point']"


