---
# tasks file for change_hostname
# Меняем имя ВМ, если имя в inventory.yaml отличается от фактического
- name: Изменение имени ВМ
  shell: "echo {{ inventory_hostname }} > /etc/hostname"
  when: "inventory_hostname != ansible_hostname"
  notify: "vm_reboot"