---
# vars file for mediawiki
packages_to_install:
  - nginx
  - php 
  - php-intl
  - php-mbstring
  - php-xml
  - php-apcu 
  - php-curl
  - php8.1-fpm
  - php8.1-pgsql
  - postgresql
  - postgresql-contrib
  - python3-psycopg2
  - acl
  - rsync
  - python3
  - python3-venv
  - python3-pip
