---
# handlers file for change_hostname
- name: "vm_reboot"
  reboot:
    reboot_timeout: 100  # Timeout in seconds
    test_command: uptime  # Command to check availability after reboot
  listen: "vm_reboot"