---
# tasks file for zabbix_server_monitoring_system

# =========================
# Block Zabbix-Server setup
# =========================

# Adding secret variables
- name: Step 1 - Adding secret variables
  include_vars: "{{ playbook_dir }}/common_files/ansible_secrets.yaml"
  tags:
    - zabbix_server_setup_adding_secret_variables

# Downloading the Zabbix repository
- name: Step 2 - Downloading the Zabbix repository
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb
    dest: /tmp/zabbix_all.deb
  tags:
    - zabbix_server_setup_downloading_zabbix_repository

# Installing Zabbix repository
- name: Step 3 - Installing Zabbix repository
  ansible.builtin.apt:
    deb: /tmp/zabbix_all.deb
  tags:
    - zabbix_server_setup_installing_zabbix_repository


# Updating the apt repository
- name: Step 4 - Update list of packages
  apt:
    update_cache: yes
  become: true
  tags:
    - zabbix_server_setup_apt_updating

# Installing apt packages
- name: Step 5 - Apt packages installing
  apt:
    name: "{{ item }}" 
    state: present
  loop:
    - "{{ apt_packages_to_install }}"
  tags:
    - zabbix_server_setup_apt_installing


# Importing initial schema for Zabbix server
- name: Step 6 - Importing initial schema for Zabbix server
  become_user: zabbix
  ansible.builtin.shell: |
    PGPASSWORD={{ postgres_zabbix_server_user_vars.db_user_password }} zcat /usr/share/zabbix-sql-scripts/postgresql/server.sql.gz | psql -U zabbix -d zabbix
  tags:
    - zabbix_server_setup_import_initial_schema


# Configuring the "DBPassword" in /etc/zabbix/zabbix_server.conf 
- name: Step 7 - Configuring the "DBPassword" in /etc/zabbix/zabbix_server.conf 
  become: true
  ansible.builtin.replace:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^#?\s*DBPassword\s*=.*'
    replace: "DBPassword = {{ postgres_zabbix_server_user_vars.db_user_password }}"
  notify: restart_zabbix_server
  tags:
    - zabbix_server_setup_add_dbpassword


# Configuring the "listen" in /etc/zabbix/nginx.conf
- name: Step 8 - Configuring the "listen" in /etc/zabbix/nginx.conf
  become: true
  ansible.builtin.replace:
    path: /etc/zabbix/nginx.conf
    regexp: '^#?\s*listen\s*.*'
    replace: '        listen 8080;'
  notify: restart_zabbix_server
  tags:
    - zabbix_server_setup_add_listen

# Configuring the "server_name" in /etc/zabbix/nginx.conf
- name: Step 9 - Configuring the "server_name" in /etc/zabbix/nginx.conf
  become: true
  ansible.builtin.replace:
    path: /etc/zabbix/nginx.conf
    regexp: '^#?\s*server_name\s*.*'
    replace: '        server_name monitoring-wiki.ddns.net;'
  notify: restart_zabbix_server
  tags:
    - zabbix_server_setup_add_server_name


# Restarting and enabling packages
- name: Step 10 - Restarting and enabling packages
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}" 
    state: restarted
    enabled: yes
  loop: "{{ packages_to_restart }}"
  tags:
    - zabbix_server_setup_restarting_enabling_packages

