---
# tasks file for nginx_mediawiki_proxy

# Обновление пакетного репозитория 
- name: Step 1 - Update list of packages
  apt:
    update_cache: yes
  become: yes
  tags:
    - ssetup_nginx_mediawiki_proxy_apt_update

# Установка пакетов
- name: Step 2 - Install packages
  become: true
  become_user: root
  apt:
    name: "{{ item }}" 
    state: present
  loop:
    - "{{ packages_to_install }}"
  tags:
    - setup_nginx_mediawiki_proxy_install_packages 


# Запуск сервиса nginx и добавление в автозапуск
- name: Step 3 - Start and enable nginx services
  become: true
  become_user: root
  service: 
    name=nginx
    state=started 
    enabled=yes
  tags:
    - setup_nginx_mediawiki_proxy_start_enable_nginx_service


# Удаление symlink (символической ссылки) "default" из /etc/nginx/sites-enabled/default
- name: Step 4 - Remove symlink to default nginx conf from /etc/nginx/sites-enabled/default
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags:
    - setup_nginx_mediawiki_proxy_remove_symlink_default_nginx_conf


# Копирование конфигурационного файла nginx в /etc/nginx/sites-available/nginx_mediawiki 
- name: Step 5 - Copy nginx configuration file to /etc/nginx/sites-available/nginx_mediawiki  
  become: true
  become_user: root
  copy:
    src: "{{ role_path }}/files/{{ vm_2_nginx_proxy_server.nginx_conf_name }}" 
    dest: /etc/nginx/sites-available/
    force: yes
  notify: restart_nginx
  when: nginx_mediawiki_hosts.nginx_mediawiki_proxy in inventory_hostname
  tags:
    - setup_nginx_mediawiki_proxy_copy_nginx_configuration_file


# Создание symlink (символической ссылки) из /etc/nginx/sites-available/mediawiki в /etc/nginx/sites-enabled/mediawiki
- name: Step 6 - Symlink creation for Nginx mediawiki conf file to /etc/nginx/sites-enabled/mediawiki
  become_user: root
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ vm_2_nginx_proxy_server.nginx_conf_name }}"
    dest: "/etc/nginx/sites-enabled/{{ vm_2_nginx_proxy_server.nginx_conf_name }}"
    state: link
  notify: restart_nginx
  when: nginx_mediawiki_hosts.nginx_mediawiki_proxy in inventory_hostname
  tags:
    - setup_nginx_mediawiki_proxy_symlink_creation_mediawiki