---
# ==============================================================================
# Block with Nginx Proxy Server Setup (load balancing between MediaWiki servers)
# ==============================================================================


# Updating the apt repository
- name: Step 1 - Update list of packages
  apt:
    update_cache: yes
  become: true
  tags:
    - nginx_proxy_mediawiki_setup_apt_Updating

# Installing apt packages
- name: Step 2 - Apt packages installing
  apt:
    name: "{{ item }}" 
    state: present
  loop:
    - "{{ apt_packages_to_install }}"
  tags:
    - nginx_proxy_mediawiki_setup_installing_apt_packages 


# Starting and enabling the nginx services
- name: Step 3 - Starting and enabling the nginx services
  become: true
  become_user: root
  ansible.builtin.service: 
    name: nginx
    state: started 
    enabled: yes
  tags:
    - nginx_proxy_mediawiki_setup_start_enable_nginx_service


# Removing the "default" symlink from /etc/nginx/sites-enabled/default
- name: Step 4 - Removing the "default" symlink from /etc/nginx/sites-enabled/default
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags:
    - nginx_proxy_mediawiki_setup_remove_symlink_default_nginx_conf


# Copying the nginx_mediawiki_proxy configuration file to /etc/nginx/sites-available/ with '0755' permissions
# Owner: rwx (read, write, and execute)
# Group: r-x (read and execute)
# Others: r-x (read and execute)
- name: Step 5 - Copying the nginx_mediawiki_proxy configuration file to /etc/nginx/sites-available/ with '0755' permissions
  become: true
  become_user: root
  copy:
    src: "{{ playbook_dir }}/common_files/nginx_proxy/nginx_mediawiki_proxy"
    dest: /etc/nginx/sites-available/
    mode: '0755'
  notify: restart_nginx
  tags:
    - nginx_proxy_mediawiki_setup_copying_nginx_mediawiki_configuratiion_file

# Creating a symlink for nginx_mediawiki_proxy configuration file from /etc/nginx/sites-available/nginx_mediawiki_proxy to /etc/nginx/sites-enabled/nginx_mediawiki_proxy
# /etc/nginx/sites-enabled/nginx_mediawiki_proxy >> ../sites-available/nginx_mediawiki_proxy"
- name: Step 6 - Symlink creation for nginx_mediawiki_proxy configuration file from /etc/nginx/sites-available/nginx_mediawiki_proxy to /etc/nginx/sites-enabled/nginx_mediawiki_proxy
  become_user: root
  become: true
  ansible.builtin.file:
    src: "../sites-available/nginx_mediawiki_proxy"
    dest: "/etc/nginx/sites-enabled/nginx_mediawiki_proxy"
    state: link
  notify: restart_nginx
  tags:
    - nginx_proxy_mediawiki_setup_creation_symlink_nginx_mediawiki_configuration_file


# Copying nginx.conf (with additional logs settings) to /etc/nginx/
- name: Step 7 - Copying nginx.conf (with additional logs settings) to /etc/nginx/
  become: true
  become_user: root
  copy:
    src: "{{ playbook_dir }}/common_files/nginx_proxy/nginx.conf"
    dest: /etc/nginx/
    force: yes
  notify: restart_nginx
  tags:
    - nginx_proxy_mediawiki_setup_copy_nginx_conf


# Restarting the Nginx service
- name: Step 8 - Restarting the Nginx service
  become: true
  become_user: root
  systemd:
    name: nginx
    state: restarted
  tags:
    - nginx_proxy_mediawiki_setup_restart_nginx_service