--- 
# vars file for default_packages
packages_to_install:
  - dnsutils
  - net-tools
  - libldap-2.5-0
  - zabbix-agent
  - rsync
  - rsyslog
  - mc
  - curl
  - wget
  - apt-transport-https
  - gnupg2
  - software-properties-common
  - ca-certificates
  - parted
  - openssh-server 