linuxVM:
  children:
    monitoringSystem:
      hosts:
        vm-1-monitoring-system:
          ansible_host: 89.169.159.61
          external_disks:
          - disk_id: fhm0hf9md7ef4is0j0dn
            disk_name: vhdd-1-monitoring-system-db
            mount_point: /mnt/vhdd-1-monitoring-system-db
            filesystem: ext4
    nginxProxyServer:
      hosts:
        vm-2-nginx-proxy-server:
          ansible_host: 89.169.130.120
    mediawikiServer:
      hosts:
        vm-3-mediawiki-server-1:
          ansible_host: 89.169.159.99
        vm-4-mediawiki-server-2:
          ansible_host: 89.169.130.46
    haproxyProxyServer:
      hosts:
        vm-5-haproxy-proxy-server:
          ansible_host: 89.169.128.244
    primaryDb:
      hosts:
        vm-6-primary-db:
          ansible_host: 89.169.133.9
          external_disks:
          - disk_id: fhmjqefgan8707pt3shj
            disk_name: vssd-1-primary-db
            mount_point: /mnt/vssd-1-primary-db
            filesystem: ext4
    standbyDb:
      hosts:
        vm-7-standby-db:
          ansible_host: 89.169.140.244
          external_disks:
          - disk_id: fhmkjo4icfs2pbd9i1d2
            disk_name: vhdd-2-standby-db
            mount_point: /mnt/vhdd-2-standby-db
            filesystem: ext4
          - disk_id: fhm65nsh4d9kosf1t7u6
            disk_name: vhdd-3-dump-db
            mount_point: /mnt/vhdd-3-dump-db
            filesystem: ext4
  vars:
    ansible_user: root
    ansible_password: ''
    connection_protocol: ssh
    ansible_become: false
