---
- name: test
  hosts: vm-1-monitoring-system
  become: true
  tasks:


    - name: Create a new ext4 primary partition
      community.general.parted:
        device: /dev/disk/by-id/virtio-fhm9pe2fdj53cr0r4gut
        number: 1
        state: present
        fs_type: ext4
        part_start: '0%'
        part_end: '100%'


    # - name: Remove partition number 1
    #   community.general.parted:
    #     device: /dev/disk/by-id/virtio-fhm9pe2fdj53cr0r4gut
    #     number: 1
    #     state: absent


    # ls -la /dev/disk/by-id
    # lsblk
    # lsblk -f