---
- name: LVM Testing
  hosts: vm-1-monitoring-system
  become: true
  gather_facts: False
  tasks:
    # Создание раздела
    # Проверка создания раздела "lsblk"
    - name: Partition /dev/vdb disk
      community.general.parted:
        device: /dev/vdb
        number: 1
        flags: [ lvm ]
        label: "gpt"
        state: present
        part_end: "100%"

    # Создание Volume Group
    # Проверка: "vgs"
    - name: Task for PV and VG
      community.general.lvg:
          vg: vg-db-storage
          pvs: /dev/vdb1

    # Создание Logical Volume
    # Проверка: "lvs"
    - name: Logical volume with size
      community.general.lvol:
        vg: vg-db-storage
        lv: lv-vhdd-1-monitoring-system-db
        size: 100%FREE
    
    # Форматирование раздела и создание файловой системы
    # Проверка: "lsblk -f"
    - name: Format the volume with ext4 fs
      community.general.filesystem:
        fstype: ext4
        dev: /dev/vg-db-storage/lv-vhdd-1-monitoring-system-db
    
    # Создание директории для монтирования жеского диска
    - name: Target directory under /opt/
      ansible.builtin.file:
        path: /opt/vhdd-1-monitoring-system-db/
        state: directory
        mode: '0755'
    
    # Монтирование жеского диска
    # Проверка, что жеский диск смонтирован "lsblk -f" 
    # Проверка, что жесткий диск добавлен в автозагрузку "cat /etc/fstab"
    # Проверка, что все файловые системы из "/etc/fstab" корректно монтируются
    - name: mount the lv on /opt/vhdd-1-monitoring-system-db/
      ansible.posix.mount:
        path: /opt/vhdd-1-monitoring-system-db/
        src: /dev/vg-db-storage/lv-vhdd-1-monitoring-system-db
        fstype: ext4
        state: mounted

