--- 

# Меняем имя ВМ, если имя в inventory.yaml отличается от фактического
- name: Change VM hostname
  hosts: all
  roles:
    - role: change_hostname
  tags:
    - change_hostname

# Монтирование и инициализация внешних жестких дисков
- name: Mount external disks 
  # hosts: vm-1-monitoring-system, vm-6-primary-db, vm-7-standby-db
  hosts: "{{ target_groups }}"
  # hosts: all
  roles:
    - role: mount_disk
  tags:
    - mount_external_disks

# Размонтирование и деинициализация внешних жестких дисков
- name: Unmount external disks 
  hosts: "{{ target_groups }}"
  roles:
    - role: unmount_disk
  tags:
    - unmount_external_disks

# Инициализация и настройка postgresql
- name: Set up db_postgresql
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: db_postgresql
  tags:
    - setup_db_postgresql

