--- 

# Меняем имя ВМ, если имя в inventory.yaml отличается от фактического
- name: Change VM hostname
  hosts: all
  roles:
    - role: change_hostname
  tags:
    - change_hostname

# Монтирование и инициализация внешних жестких дисков
- name: Mount external disks 
  # hosts: vm-1-monitoring-system, vm-6-primary-db, vm-7-standby-db
  hosts: "{{ target_groups }}"
  # hosts: all
  roles:
    - role: mount_disk
  tags:
    - mount_external_disks

# Размонтирование и деинициализация внешних жестких дисков
- name: Unmount external disks 
  hosts: "{{ target_groups }}"
  roles:
    - role: unmount_disk
  tags:
    - unmount_external_disks

# Инициализация и общая настройка postgresql
- name: Set up db_postgresql
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: db_postgresql
  tags:
    - setup_db_postgresql

# Настройка primary postgresql
- name: Set up primary db_postgresql
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: db_postgresql_primary
  tags:
    - setup_db_primary_postgresql

# Настройка standby postgresql
- name: Set up standby db_postgresql
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: db_postgresql_standby
  tags:
    - setup_db_standby_postgresql


# Настройка zabbix-server postgresql
- name: Set up zabbix-server db_postgresql
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: db_postgresql_zabbix_server
  tags:
    - setup_db_postgresql_zabbix_server


# Настройка mediawiki
- name: Set up mediawiki servers
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: mediawiki
  tags:
    - setup_mediawiki

# Настройка nginx mediawiki proxy
- name: Set up nginx mediawiki proxy
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: nginx_mediawiki_proxy
  tags:
    - setup_nginx_mediawiki_proxy


# Настройка zabbix-server monitoring system
- name: Set up zabbix-server monitoring system
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: zabbix_server_monitoring_system
  tags:
    - setup_zabbix_server_monitoring_system


# Настройка zabbix-agent monitoring system
- name: Set up zabbix-agent monitoring system
  hosts: all
  become: true
  roles:
    - role: zabbix_agent_monitoring_system
  tags:
    - setup_zabbix_agent_monitoring_system