--- 

# Compare the current VM hostname with inventory.yaml and change it if it differs
- name: Changing the hostnames of all VMs
  hosts: all
  roles:
    - role: change_hostname
  tags:
    - change_vms_hostname

# Mounting external hard drives and initializing LVM
- name: Mounting external hard drives 
  hosts: "{{ target_vms }}"
  roles:
    - role: mount_disk
  tags:
    - mount_external_hard_drives

# Unmounting external hard drives and deinitializing LVM
- name: Unmounting external hard drives 
  hosts: "{{ target_vms }}"
  roles:
    - role: unmount_disk
  tags:
    - unmount_external_hard_drives

# PostgreSQL Common Setup
- name: PostgreSQL Common Setup
  hosts: "{{ target_vms }}"
  become: true
  roles:
    - role: db_postgresql
  tags:
    - postgresql_common_setup

# Primary PostgreSQL Setup
- name: Primary PostgreSQL db Setup
  hosts: "{{ target_vms }}"
  become: true
  roles:
    - role: db_postgresql_primary
  tags:
    - primary_postgresql_setup

# Standby PostgreSQL Setup
- name: Set up standby db_postgresql
  hosts: "{{ target_vms }}"
  become: true
  roles:
    - role: db_postgresql_standby
  tags:
    - standby_postgresql_setup

# Zabbix-Server PostgreSQL Setup
- name: Zabbix-Server PostgreSQL Setup
  hosts: "{{ target_vms }}"
  become: true
  roles:
    - role: db_postgresql_zabbix_server
  tags:
    - zabbix_server_postgresql_setup

# DDNS Noip DUC Setup 
- name: DDNS Noip DUC Setup 
  hosts: "{{ ddns_hosts }}"
  become: true
  roles:
    - role: ddns_duc
  tags:
    - ddns_duc_setup


# MediaWiki Setup
- name: MediaWiki Setup
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: mediawiki
  tags:
    - mediawiki_setup

# Nginx-proxy MediaWiki Setup
- name: Nginx-proxy MediaWiki Setup
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: nginx_mediawiki_proxy
  tags:
    - nginx_proxy_mediawiki_setup


# Zabbix-Server Setup
- name: Zabbix-Server Setup
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: zabbix_server_monitoring_system
  tags:
    - zabbix_server_setup


# Zabbix-Agent Setup
- name: Zabbix-Agent Setup
  hosts: "{{ target_groups }}"
  become: true
  roles:
    - role: zabbix_agent_monitoring_system
  tags:
    - zabbix_agent_setup