# Инфо:

# 1. Размонтирование директории: 
# 1.1. Просмотреть path точки монтирования: lsblk -f
# 1.2. Размонтировать директорию: umount <path>
# umount /opt/vhdd-1-monitoring-system-db/

# 2. Удалить Logical Volume:
# 2.1. Просмотреть Logical Volume: lvdisplay
# 2.2. Удалить Logical Volume: lvremove <path>
# lvremove /dev/vg-db-storage/lv-vhdd-1-monitoring-system-db

# 3. Удалить Volume Group:
# 3.1. Просмотреть Volume Group: vgdisplay
# 3.2. Удалить Volume Group: vgremove <name>
# vgremove vg-db-storage

# 4. Удалить partition (и вместе с ним physical volume):
# 4.1. Просмотреть partition: fdisk -l -a или lsblk -f
# 4.2. Удалить Volume Group: fdisk <path> 
# fdisk /dev/vdb далее p (просмотр сущ. разделов) далее d (удалить раздел) далее выбрать номер раздела далее w (сохранить изменени

---
- name: Cleanup LVM and partitions
  hosts: vm-1-monitoring-system
  become: true
  tasks:
    # 1. Unmount the logical volume if mounted
    - name: Unmount the logical volume
      ansible.posix.mount:
        path: /opt/vhdd-1-monitoring-system-db  # Path to the mount point
        state: unmounted

    # 2. Remove the Logical Volume
    - name: Remove logical volume
      community.general.lvol:
        vg: vg-db-storage
        lv: lv-vhdd-1-monitoring-system-db
        state: absent
        force: true

    # 3. Remove the Volume Group
    - name: Remove volume group
      community.general.lvg:
        vg: vg-db-storage
        state: absent

    # 4. Remove the partition using fdisk
    - name: Partition /dev/vdb disk
      community.general.parted:
        device: /dev/vdb
        number: 1
        state: absent