---
# tasks file for zabbix_agent_and_proxy

- name: Обновление списка пакетов
  apt:
    update_cache: yes
  become: yes
  tags:
    - update_cache

- name: Установка программ
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ packages_to_install }}"
  tags:
    - install_zabbix_packages

# Настройка keepalived
- name: Настройка keepalived_master
  ansible.builtin.template:
    src: keepalived_master.conf.j2
    dest: /etc/keepalived/keepalived.conf
  when: inventory_hostname == 'vm-2'
  tags:
    - keepalived_master_settings

- name: Настройка keepalived_backup
  ansible.builtin.template:
    src: keepalived_backup.conf.j2
    dest: /etc/keepalived/keepalived.conf
  when: inventory_hostname == 'vm-3'
  tags:
    - keepalived_backup_settings

- name: Перезагрузка и добавление keepalived в автозагрузку
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: yes
  tags:
    - keepalived_restart_and_enable

# Настройка PostgreSQL
- name: Установка PostgreSQL
  ansible.builtin.package:
    name:
      - postgresql
      - postgresql-contrib
    state: present
  become: yes
  tags:
    - install_postgresql

- name: Запуск службы PostgreSQL
  ansible.builtin.service:
    name: postgresql
    state: started
    enabled: yes
  become: yes
  tags:
    - start_postgresql

- name: Изменение метода аутентификации для всех пользователей на md5
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf  # Убедитесь, что путь правильный
    regexp: '^local\s+all\s+all\s+peer'
    line: 'local   all             all                                     md5'
  become: yes
  notify: restart_PostgreSQL
  tags:
    - configure_pg_hba_all_users


- name: Изменение метода аутентификации для пользователя zabbix на md5
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    regexp: '^local\s+all\s+zabbix\s+peer'
    line: 'local   all             zabbix                                  md5'
  become: yes
  notify: restart_PostgreSQL
  tags:
    - configure_pg_hba_zabbix

- name: Изменение метода аутентификации для пользователя postgres на md5
  ansible.builtin.lineinfile:
    path: /etc/postgresql/14/main/pg_hba.conf
    regexp: '^local\s+all\s+postgres\s+peer'
    line: 'local   all             postgres                                md5'
  become: yes
  notify: restart_PostgreSQL
  tags:
    - configure_pg_hba_postgres
    
# Настройка базы данных
- name: Создание базы данных для Zabbix
  ansible.builtin.postgresql_db:
    name: "{{ postgresql_data.db_name }}"
    login_user: "{{ postgresql_data.db_user }}"
    login_password: "{{ postgresql_data.db_password }}"  # Пароль суперпользователя
    state: present
  tags:
    - create_zabbix_db

- name: Создание пользователя для Zabbix
  ansible.builtin.postgresql_user:
    name: "{{ postgresql_data.db_user }}"
    password: "{{ postgresql_data.db_password }}"
    state: present
  become_user: postgres
  tags:
    - create_zabbix_user

- name: Предоставление прав пользователю на базу данных
  ansible.builtin.postgresql_privs:
    db: "{{ postgresql_data.db_name }}"
    role: "{{ postgresql_data.db_user }}"
    type: database
    privs: ALL
  become_user: postgres
  tags:
    - grant_privileges

# Настройка Zabbix server
- name: Настройка zabbix-server
  ansible.builtin.template:
    src: zabbix_server.conf.j2
    dest: /etc/zabbix/zabbix_server.conf
  tags:
    - zabbix_server_settings

- name: Запуск службы zabbix_server
  ansible.builtin.service:
    name: zabbix_server
    state: started
    enabled: yes
  become: yes
  tags:
    - start_zabbix_server

- name: Перезагрузка и добавление zabbix_server в автозагрузку
  ansible.builtin.service:
    name: zabbix_server
    state: restarted
    enabled: yes
  tags:
    - zabbix_server_restart_and_enable

# Настройка Zabbix agent
- name: Настройка zabbix-agent
  ansible.builtin.template:
    src: zabbix_agentd.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  tags:
    - zabbix_agent_settings

- name: Перезагрузка и добавление zabbix-agent в автозагрузку
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted
    enabled: yes
  tags:
    - zabbix_agent_restart_and_enable
