---
# tasks file for default_packages

- name: Обновление списка пакетов
  apt:
    update_cache: yes
  become: yes

- name: Установка программ #Имя задачи 
  apt: #Используемый модуль
    name: "{{ item }}" #Имя пакета из цикла
    state: present #Параметр действия. present - установить, absent - удалить
  loop:
    - "{{ packages_to_install }}" #Цикл будет перебирать все значения из переменной "packages"

- name: Настройка keepalived_master
  ansible.builtin.template:
    src: keepalived_master.conf.j2
    dest: /etc/keepalived/keepalived.conf
  when: inventory_hostname == 'vm-2'  # Условие для выполнения на vm-2

- name: Настройка keepalived_backup
  ansible.builtin.template:
    src: keepalived_backup.conf.j2
    dest: /etc/keepalived/keepalived.conf
  when: inventory_hostname == 'vm-3'  # Условие для выполнения на vm-3

- name: Restarting and enabling keepalived
  ansible.builtin.service:
    name: keepalived
    state: restarted
    enabled: yes 


    