---
# handlers file for db_postgresql_standby

- name: Postgresql Restarter
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes
  listen: "restart_postgresql"

- name: Cron Restarter
  ansible.builtin.service:
    name: cron
    state: restarted
    enabled: yes
  listen: "restart_cron"