---
# handlers file for db_postgresql_standby

- name: Postgresql Reloader
  ansible.builtin.service:
    name: postgresql
    state: restarted
    enabled: yes
  listen: "reload_postgresql"

- name: Cron Reloader
  ansible.builtin.service:
    name: cron
    state: restarted
    enabled: yes
  listen: "reload_cron"