site_name: MediaWiki Doc Management Service
site_url: https://vepsong.github.io/MediaWiki-Doc-Management-Service/

nav:
  - Getting started:
      - 1. Introduction: index.md
      - 2. App deployment schema: 2. app_deploy_schema_v4.md
  - Service VM configuration:
      - 3. Service VM Docker Configuration: 3.1. service_vm_docker_setup.md
      - 4. Yandex Cloud CLI profile and Service Account Setup: 4.1. yandex_cloud_cli_and_serv_acc_setup.md
      - 5. Yandex Cloud Terraform Setup: 5.1. yandex_cloud_terraform_setup.md
  - Remote deployment using Ansible:
      - 6. Ansible Setup: 6.1. ansible_setup.md
      - 7. Run the Ansible pipeline: 7.1. ansible_pipeline.md
  - Refining the scenario for Primary PostgreSQL DB failure:
      - 8. Manual failover from the Primary PostgreSQL to the Standby PostgreSQL: 8.1. manual_failover_from_primary_to_standby_db.md

theme:
  name: readthedocs
  highlightjs: true
  custom_dir: overrides
  hljs_languages:
      - yaml
      - rust
      - bash

extra:
  alternate:
    - name: English
      link: /en/
      lang: en
  github_link: "https://github.com/vepsong/MediaWiki-Doc-Management-Service"
  production_year: 2024
  author_name: Dmitry Kirsanov

extra_css:
    - css/extra.css

copyright: Copyright &copy;

plugins:
  - search
  - macros
  - include-markdown

markdown_extensions:
    - pymdownx.snippets: