site_name: Wikimedia project documentation
docs_dir: '../../docs/en'  
site_dir: '../../generated/en'

nav:
  - Home: index.md
  - About: about.md


theme:
  name: readthedocs
  custom_dir: '../../overrides/' 
  favicon: assets/images/favicon.ico  
  language: en 

extra:                                              # Language Selection
  alternate:  

      # Switch to English
    - name: English
      link: /en/
      lang: en

    # Switch to Dutch
    - name: Russian
      link: /ru/
      lang: ru


plugins:
  - search:                                         
      lang: en                                      # Set language for search
