---
# tasks file for zabbix_agent_monitoring_system

# =========================
# Block Zabbix-Agent setup
# =========================

# Downloading the Zabbix repository
- name: Step 1 - Downloading the Zabbix repository
  ansible.builtin.get_url:
    url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu22.04_all.deb
    dest: /tmp/zabbix_all.deb
  tags:
    - zabbix_agent_setup_download_zabbix_repository

# Installing the Zabbix repository
- name: Step 2 - Installing the Zabbix repository
  ansible.builtin.apt:
    # deb: /tmp/zabbix-release_latest+ubuntu22.04_all.deb
    deb: /tmp/zabbix_all.deb
  tags:
    - zabbix_agent_setup_install_zabbix_repository

# Updating the apt repository
- name: Step 3 - Updating the apt repository
  apt:
    update_cache: yes
  become: true
  tags:
    - zabbix_agent_setup_apt_update

# Installing apt packages
- name: Step 4 - Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ item }}" 
    state: present
  loop: "{{ apt_packages_to_install }}"
  tags:
    - zabbix_agent_setup_install_packages


# Configuring the "Server" in /etc/zabbix/zabbix_agentd.conf 
- name: Step 5 - Configuring the "Server" in /etc/zabbix/zabbix_agentd.conf 
  become: true
  ansible.builtin.replace:
    path: /etc/zabbix/zabbix_agentd.conf 
    regexp: '^Server=.*$'
    replace: "Server={{ hostvars['vm-1-zabbix-server'].ip_addr }}"
  tags:
    - zabbix_agent_setup_add_server_name


# Configuring the "ServerActive" in /etc/zabbix/zabbix_agentd.conf 
- name: Step 6 - Configuring the "ServerActive" in /etc/zabbix/zabbix_agentd.conf 
  become: true
  ansible.builtin.replace:
    path: /etc/zabbix/zabbix_agentd.conf 
    regexp: '^ServerActive=.*$'
    replace: "ServerActive={{ hostvars['vm-1-zabbix-server'].ip_addr }}"
  tags:
    - zabbix_agent_setup_add_server_active




# Configuring the "Hostname" in /etc/zabbix/zabbix_agentd.conf 
- name: Step 7 - Configuring the "Hostname" in /etc/zabbix/zabbix_agentd.conf 
  become: true
  ansible.builtin.replace:
    path: /etc/zabbix/zabbix_agentd.conf 
    regexp: '^Hostname=.*$'
    replace: "Hostname={{ ansible_hostname }}"
  tags:
    - zabbix_agent_setup_add_server_active



# Restarting and enabling packages
- name: Step 8 - Restarting and enabling packages
  become: true
  ansible.builtin.systemd:
    name: "{{ item }}" 
    state: restarted
    enabled: yes
  loop: "{{ apt_packages_to_restart }}"
  tags:
    - zabbix_agent_setup_restarting_enabling_packages
