---
# =================================
# Block with MediaWiki common tasks
# =================================

# Updating the apt repository
- name: Step 1 - Update list of packages
  apt:
    update_cache: yes
  become: true
  tags:
    - mediawiki_setup_apt_update

# Installing apt packages
- name: Step 2 - Apt packages installing
  apt:
    name: "{{ item }}" 
    state: present
  loop:
    - "{{ apt_packages_to_install }}"
  tags:
    - mediawiki_setup_install_apt_packages 


# Installing the pip3 packages
- name: Step 3 - Pip3 packages installing
  become: true
  ansible.builtin.pip:
    name: "{{ item }}" 
    state: latest
  loop:
    - "{{ pip3_packages_to_install }}"
  tags:
    - mediawiki_setup_install_pip3_packages


# Adding secret variables
- name: Step 4 - Adding secret variables
  include_vars: "{{ playbook_dir }}/common_files/ansible_secrets.yaml"
  tags:
    - mediawiki_setup_adding_secret_variables


# Starting and enabling the nginx services
- name: Step 5 - Starting and enabling the nginx services
  service: 
    name=nginx
    state=started 
    enabled=yes
  tags:
    - mediawiki_setup_start_enable_nginx_service


# Starting and enabling the postgresql service
- name: Step 6 - Starting and enabling the postgresql service
  service: 
    name=postgresql
    state=started 
    enabled=yes
  tags:
    - mediawiki_setup_start_enable_postgresql_service


# Removing the "default" symlink from /etc/nginx/sites-enabled/default
- name: Step 7 - Removing the "default" symlink from /etc/nginx/sites-enabled/default
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags:
    - setup_mediawiki_remove_symlink_default_nginx_conf





# # Копирование конфигурационного файла nginx в /etc/nginx/sites-available/nginx_mediawiki 
# - name: Step 6 - Copy nginx configuration file to /etc/nginx/sites-available/nginx_mediawiki  
#   become: true
#   become_user: root
#   copy:
#     src: "{{ role_path }}/files/{{ vm_3_mediawiki_server_1.nginx_conf_name }}" 
#     dest: /etc/nginx/sites-available/
#   notify: restart_nginx
#   tags:
#     - setup_mediawiki_copy_nginx_configuration_file

# # Создание symlink (символической ссылки) из /etc/nginx/sites-available/mediawiki в /etc/nginx/sites-enabled/mediawiki
# - name: Step 7 - Symlink creation for Nginx mediawiki conf file to /etc/nginx/sites-enabled/mediawiki
#   become_user: root
#   become: true
#   ansible.builtin.file:
#     src: "/etc/nginx/sites-available/{{ vm_3_mediawiki_server_1.nginx_conf_name }}"
#     dest: "/etc/nginx/sites-enabled/{{ vm_3_mediawiki_server_1.nginx_conf_name }}"
#     state: link
#   notify: restart_nginx
#   tags:
#     - setup_mediawiki_symlink_creation_mediawiki


# =============================================================
# Block with MediaWiki Server-1 tasks (vm-3-mediawiki-server-1)
# =============================================================


# Копирование конфигурационного файла nginx в /etc/nginx/sites-available/nginx_mediawiki 
- name: Step 7 - Copy nginx configuration file to /etc/nginx/sites-available/nginx_mediawiki  
  become: true
  become_user: root
  copy:
    src: "{{ role_path }}/files/{{ vm_3_mediawiki_server_1.nginx_conf_name }}" 
    dest: /etc/nginx/sites-available/
  notify: restart_nginx
  when: mediawiki_hosts.server1 in inventory_hostname
  tags:
    - setup_mediawiki_copy_nginx_configuration_file
    - setup_mediawiki_add_secret_variables, setup_mediawiki_copy_nginx_configuration_file

# Создание symlink (символической ссылки) из /etc/nginx/sites-available/mediawiki в /etc/nginx/sites-enabled/mediawiki
- name: Step 8 - Symlink creation for Nginx mediawiki conf file to /etc/nginx/sites-enabled/mediawiki
  become_user: root
  become: true
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ vm_3_mediawiki_server_1.nginx_conf_name }}"
    dest: "/etc/nginx/sites-enabled/{{ vm_3_mediawiki_server_1.nginx_conf_name }}"
    state: link
  notify: restart_nginx
  when: mediawiki_hosts.server1 in inventory_hostname
  tags:
    - setup_mediawiki_symlink_creation_mediawiki
    - setup_mediawiki_add_secret_variables, setup_mediawiki_symlink_creation_mediawiki


# Скачивание архива с MediaWiki в /var/www/
- name: Step 9 - Download MediaWiki archive to /var/www/
  become: true
  become_user: "{{ secret_vm_3_mediawiki_server_1.user }}"
  ansible.builtin.get_url:
    url: "{{ vm_3_mediawiki_server_1.mediawiki_download_link }}"
    dest: "{{ vm_3_mediawiki_server_1.mediawiki_parent_path }}"
  when: mediawiki_hosts.server1 in inventory_hostname
  tags:
    - setup_mediawiki_download_mediaWiki_archive
    - setup_mediawiki_add_secret_variables, setup_mediawiki_download_mediaWiki_archive

# Распаковка архива c MediaWiki в /var/www/
- name: Step 10 - Unzip MediaWiki archive to /var/www/
  become: true
  become_user: "{{ secret_vm_3_mediawiki_server_1.user }}"
  ansible.builtin.unarchive:
    src: "{{ vm_3_mediawiki_server_1.mediawiki_parent_path }}{{ vm_3_mediawiki_server_1.mediawiki_archive_name }}"
    dest: "{{ vm_3_mediawiki_server_1.mediawiki_parent_path }}"
    remote_src: yes
  when: mediawiki_hosts.server1 in inventory_hostname
  tags:
    - setup_mediawiki_unzip_mediaWiki_archive
    - setup_mediawiki_add_secret_variables, setup_mediawiki_unzip_mediaWiki_archive

# Переименование разархивированной паки c MediaWiki в /var/www/mediawiki
- name: Step 11 - Rename unzipped folder to /var/www/mediawiki
  become: true
  become_user: "{{ secret_vm_3_mediawiki_server_1.user }}"
  ansible.builtin.command:
    cmd: "mv {{ vm_3_mediawiki_server_1.mediawiki_parent_path }}{{ vm_3_mediawiki_server_1.mediawiki_unzipped_folder_name }} {{ vm_3_mediawiki_server_1.mediawiki_path }}"
  when: mediawiki_hosts.server1 in inventory_hostname
  tags:
    - setup_mediawiki_rename_unzipped_mediaWiki_archive
    - setup_mediawiki_add_secret_variables, setup_mediawiki_rename_unzipped_mediaWiki_archive

# Удаление архива с MediaWiki из /var/www/mediawiki-1.42.3.tar.gz
- name: Step 12 - Remove MediaWiki archive from /var/www/mediawiki-1.42.3.tar.gz
  ansible.builtin.file:
    path: "{{ vm_3_mediawiki_server_1.mediawiki_parent_path }}{{ vm_3_mediawiki_server_1.mediawiki_archive_name }}"
    state: absent
  when: mediawiki_hosts.server1 in inventory_hostname
  tags:
    - setup_mediawiki_remove_mediaWiki_archive


# Немедленный перезапуск сервиса Nginx
- name: Step 13 - Restart Nginx service immediately
  become: true
  become_user: "{{ secret_vm_3_mediawiki_server_1.user }}"
  systemd:
    name: nginx
    state: restarted
  when: mediawiki_hosts.server1 in inventory_hostname
  tags:
    - setup_mediawiki_restart_nginx
    - setup_mediawiki_add_secret_variables, setup_mediawiki_restart_nginx

# Копирование LocalSettings.php в /var/www/mediawiki
- name: Step 14 - Copy LocalSettings.php в /var/www/mediawiki
  become: true
  become_user: "{{ secret_vm_3_mediawiki_server_1.user }}"
  copy:
    src: "{{ role_path }}/files/{{ vm_3_mediawiki_server_1.mediawiki_local_settings_file_name }}"   
    dest: "{{ vm_3_mediawiki_server_1.mediawiki_path }}"
  when: mediawiki_hosts.server1 in inventory_hostname
  tags:
    - setup_mediawiki_copy_localsettings_php_to_mediawiki
    - setup_mediawiki_add_secret_variables, setup_mediawiki_copy_localsettings_php_to_mediawiki



# =======================================
# Блок с задачами vm-4-mediawiki-server-2
# =======================================


# Создание директории /scripts, в которой будут хранится скрипты для rsync папки mediawiki
- name: Step 16 - Create directory /scripts for scripts on vm-4-mediawiki-server-2
  become: true
  become_user: "{{ secret_vm_4_mediawiki_server_2.user }}"
  ansible.builtin.file:
    path: "{{ vm_4_mediawiki_server_2.scripts_path }}"
    state: directory
    mode: '0755'
  when: mediawiki_hosts.server2 in inventory_hostname
  tags:
    - setup_mediawiki_create_path_for_scripts_folder
    - setup_mediawiki_add_secret_variables, setup_mediawiki_create_path_for_scripts_folder

# Cоздание пустого файла .env для дальнейшего наполнения значениями из secrets.yml
- name: Step 17 - Create .env file in /scripts on vm-4-mediawiki-server-2
  become: true
  become_user: "{{ secret_vm_4_mediawiki_server_2.user }}"
  ansible.builtin.file:
    path: "{{ vm_4_mediawiki_server_2.env_path }}"
    state: touch
    mode: '0644'
  when: mediawiki_hosts.server2 in inventory_hostname
  tags:
    - setup_mediawiki_create_env_file
    - setup_mediawiki_add_secret_variables, setup_mediawiki_create_env_file

# Копирование скрипта archive_remote_rsync.py в /scripts с правами на исполнение
- name: Step 18 - Copy archive_remote_rsync.py to /scripts on vm-4-mediawiki-server-2
  copy:
    src: "{{ role_path }}/files/{{ vm_4_mediawiki_server_2.remote_rsync_script_name }}" 
    dest: "{{ vm_4_mediawiki_server_2.scripts_path }}"
    mode: '0755'
  when: mediawiki_hosts.server2 in inventory_hostname
  tags:
    - setup_mediawiki_copy_archive_remote_rsync_py_to_scripts


# Наполнение .env
- name: Step 19 - Fill up .env
  become: true
  become_user: "{{ secret_vm_4_mediawiki_server_2.user }}"
  blockinfile:
    path: "{{ vm_4_mediawiki_server_2.env_path }}"
    block: |
      REMOTE_HOST={{ secret_vm_4_mediawiki_server_2.remote_host_ip }}
      REMOTE_USER={{ secret_vm_4_mediawiki_server_2.remote_user }}
      PRIVATE_KEY_PATH={{ vm_4_mediawiki_server_2.private_key_ssh_path }}
      MEDIAWIKI_REMOTE_HOST_PATH={{ vm_3_mediawiki_server_1.mediawiki_path }}
      MEDIAWIKI_DESTINATION_PATH={{ vm_4_mediawiki_server_2.mediawiki_parent_path }}
      NGINX_CONF_FILE={{ vm_4_mediawiki_server_2.nginx_conf_name }}

    marker: "# {mark} Ansible managed block for .env"
  when: mediawiki_hosts.server2 in inventory_hostname
  tags:
    - setup_mediawiki_fill_up_env
    - setup_mediawiki_add_secret_variables, setup_mediawiki_fill_up_env


# Копирование private ssh-key в ~/.ssh
# Изменение разрешений на запуск private ssh-key
- name: Step 20 - Copy Private ssh-key to ~/.ssh
  become: true
  become_user: "{{ secret_vm_4_mediawiki_server_2.user }}"
  copy:
    src: "{{ role_path }}/files/{{ vm_4_mediawiki_server_2.private_key_ssh_name}}"
    dest: "{{ vm_4_mediawiki_server_2.private_key_ssh_parent_path }}"
    mode: '600'
  when: mediawiki_hosts.server2 in inventory_hostname
  tags:
    - setup_mediawiki_copy_private_ssh_key_to_server2
    - setup_mediawiki_add_secret_variables, setup_mediawiki_copy_private_ssh_key_to_server2


# Копирование файла конфигурации /etc/logrotate.d/archive_remote_rsync
# Управление файлами логов в /scripts/archive_remote_rsync.log
# Команда для принудительного запуска logrotate - logrotate -f /etc/logrotate.conf
- name: Step 21 - Copy logrotate to /etc/logrotate.d/archive_remote_rsync
  become: true
  become_user: "{{ secret_vm_4_mediawiki_server_2.user }}"
  copy:
    src: "{{ role_path }}/files/{{ vm_4_mediawiki_server_2.logrotate_conf_name }}"
    dest: "/etc/logrotate.d/{{ vm_4_mediawiki_server_2.logrotate_conf_name }}"
  when: mediawiki_hosts.server2 in inventory_hostname
  tags:
    - setup_mediawiki_copy_logrotate
    - setup_mediawiki_add_secret_variables, setup_mediawiki_copy_logrotate


# Добавление archive_remote_rsync.py в планировшик задания cron
# minute: "0" - запуск в начале часа
# hour: "*/4" - запуск каждые 4 часа
- name: Step 22 - Run archive_remote_rsync.py script
  become: true
  become_user: "{{ secret_vm_4_mediawiki_server_2.user }}"
  ansible.builtin.cron:
    name: "Run archive_remote_rsync script"
    minute: "*"
    hour: "*"
    job: "/usr/bin/python3 {{ vm_4_mediawiki_server_2.scripts_path }}/{{ vm_4_mediawiki_server_2.remote_rsync_script_name }} >> {{ vm_4_mediawiki_server_2.scripts_path }}/{{ vm_4_mediawiki_server_2.log_file_name }} 2>&1"
  notify: restart_cron
  when: mediawiki_hosts.server2 in inventory_hostname
  tags:
    - setup_mediawiki_run_archive_remote_rsync_cron
    - setup_mediawiki_add_secret_variables, setup_mediawiki_run_archive_remote_rsync_cron