---
# =================================
# Block with MediaWiki common tasks
# =================================

# Updating the apt repository
- name: Step 1 - Update list of packages
  apt:
    update_cache: yes
  become: true
  tags:
    - mediawiki_setup_apt_update

# Installing apt packages
- name: Step 2 - Apt packages installing
  apt:
    name: "{{ item }}" 
    state: present
  loop:
    - "{{ apt_packages_to_install }}"
  tags:
    - mediawiki_setup_install_apt_packages 

# Starting and enabling the nginx services
- name: Step 3 - Starting and enabling the nginx services
  become: true
  become_user: root
  ansible.builtin.service: 
    name: nginx
    state: started 
    enabled: yes
  tags:
    - mediawiki_setup_start_enable_nginx_service

# Starting and enabling the nginx services
- name: Step 4 - Starting and enabling the postgresql service
  become: true
  become_user: root
  ansible.builtin.service: 
    name: postgresql
    state: started 
    enabled: yes
  tags:
    - mediawiki_setup_start_enable_postgresql_service

# Removing the "default" symlink from /etc/nginx/sites-enabled/default
- name: Step 5 - Removing the "default" symlink from /etc/nginx/sites-enabled/default
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  tags:
    - mediawiki_setup_remove_symlink_default_nginx_conf



# ==================================
# Block with MediaWiki Servers setup
# ==================================


# Copying the nginx_mediawiki configuration file to /etc/nginx/sites-available/ with '0755' permissions
# Owner: rwx (read, write, and execute)
# Group: r-x (read and execute)
# Others: r-x (read and execute)
- name: Step 6 - Copying the nginx_mediawiki configuration file to /etc/nginx/sites-available/ with '0755' permissions
  become: true
  become_user: root
  copy:
    src: "{{ playbook_dir }}/common_files/mediawiki_servers/nginx_mediawiki"
    dest: /etc/nginx/sites-available/
    mode: '0755'
  notify: restart_nginx
  tags:
    - mediawiki_setup_copying_nginx_mediawiki_configuratiion_file

# Creating a symlink for nginx_mediawiki configuration file from /etc/nginx/sites-available/nginx_mediawiki to /etc/nginx/sites-enabled/nginx_mediawiki
# /etc/nginx/sites-enabled/nginx_mediawiki >> ../sites-available/nginx_mediawiki"
- name: Step 7 - Symlink creation for nginx_mediawiki configuration file from /etc/nginx/sites-available/nginx_mediawiki to /etc/nginx/sites-enabled/nginx_mediawiki
  become_user: root
  become: true
  ansible.builtin.file:
    src: "../sites-available/{{ mediawiki_server.nginx_conf_name }}"
    dest: "/etc/nginx/sites-enabled/{{ mediawiki_server.nginx_conf_name }}"
    state: link
  notify: restart_nginx
  tags:
    - mediawiki_setup_creation_symlink_nginx_mediawiki_configuration_file

# Downloading the MediaWiki archive to /var/www/
- name: Step 8 - Downloading the MediaWiki archive to /var/www/
  become: true
  become_user: root
  ansible.builtin.get_url:
    url: "{{ mediawiki_server.mediawiki_download_link }}"
    dest: "{{ mediawiki_server.mediawiki_parent_path }}{{ mediawiki_server.mediawiki_archive_name }}"
  tags:
    - mediawiki_setup_downloading_mediaWiki_archive


# Unzipping the MediaWiki archive to /var/www/
- name: Step 9 - Unzipping the MediaWiki archive to /var/www/
  become: true
  become_user: root
  ansible.builtin.unarchive:
    src: "{{ mediawiki_server.mediawiki_parent_path }}{{ mediawiki_server.mediawiki_archive_name }}"
    dest: "{{ mediawiki_server.mediawiki_parent_path }}"
    remote_src: yes
  tags:
    - mediawiki_setup_unzipping_mediaWiki_archive


# Removing MediaWiki archive from /var/www/mediawiki.tar.gz
- name: Step 10 - Removing MediaWiki archive from /var/www/mediawiki.tar.gz
  become: true
  become_user: root
  ansible.builtin.file:
    path: "{{ mediawiki_server.mediawiki_parent_path }}{{ mediawiki_server.mediawiki_archive_name }}"
    state: absent
  tags:
    - mediawiki_setup_removing_mediaWiki_archive

# Copying the LocalSettings.php file to /var/www/mediawiki with '0755' permissions
- name: Step 11 - Copying the LocalSettings.php file to /var/www/mediawiki with '0755' permissions
  become: true
  become_user: root
  copy:
    src: "{{ playbook_dir }}/common_files/mediawiki_servers/LocalSettings.php"
    dest: "{{ mediawiki_server.mediawiki_parent_path }}{{ mediawiki_server.mediawiki_folder_name }}/"
    mode: '0755'
  tags:
    - mediawiki_setup_copying_localsettings_php_mediawiki_configuratiion_file


# Restarting the Nginx service
- name: Step 12 - Restarting the Nginx service
  become: true
  become_user: root
  systemd:
    name: nginx
    state: restarted
  tags:
    - mediawiki_setup_restart_nginx_service





# Alternative configuration option for MediaWiki servers
# In this setup, MediaWiki server-1 is configured first
# The remaining MediaWiki servers are configured using rsync

# # =============================================================
# # Block with MediaWiki Server-1 tasks (vm-3-mediawiki-server-1)
# # =============================================================

# # Copying the nginx_mediawiki configuration file to /etc/nginx/sites-available/ with '0755' permissions
# # Owner: rwx (read, write, and execute)
# # Group: r-x (read and execute)
# # Others: r-x (read and execute)
# - name: Step 6 - Copying the nginx_mediawiki configuration file to /etc/nginx/sites-available/ with '0755' permissions
#   become: true
#   become_user: root
#   copy:
#     src: "{{ playbook_dir }}/common_files/mediawiki_servers/nginx_mediawiki"
#     dest: /etc/nginx/sites-available/
#     mode: '0755'
#   notify: restart_nginx
#   when: mediawiki_hosts.server1 in inventory_hostname
#   tags:
#     - mediawiki_setup_copying_nginx_mediawiki_configuratiion_file


# # Creating a symlink for nginx_mediawiki configuration file from /etc/nginx/sites-available/nginx_mediawiki to /etc/nginx/sites-enabled/nginx_mediawiki
# # /etc/nginx/sites-enabled/nginx_mediawiki >> ../sites-available/nginx_mediawiki"
# - name: Step 7 - Symlink creation for nginx_mediawiki configuration file from /etc/nginx/sites-available/nginx_mediawiki to /etc/nginx/sites-enabled/nginx_mediawiki
#   become_user: root
#   become: true
#   ansible.builtin.file:
#     src: "../sites-available/{{ mediawiki_server.nginx_conf_name }}"
#     dest: "/etc/nginx/sites-enabled/{{ mediawiki_server.nginx_conf_name }}"
#     state: link
#   notify: restart_nginx
#   when: mediawiki_hosts.server1 in inventory_hostname
#   tags:
#     - mediawiki_setup_creation_symlink_nginx_mediawiki_configuration_file


# # Downloading the MediaWiki archive to /var/www/
# - name: Step 8 - Downloading the MediaWiki archive to /var/www/
#   become: true
#   become_user: root
#   ansible.builtin.get_url:
#     url: "{{ mediawiki_server.mediawiki_download_link }}"
#     dest: "{{ mediawiki_server.mediawiki_parent_path }}{{ mediawiki_server.mediawiki_archive_name }}"
#   when: server1 in inventory_hostname
#   tags:
#     - mediawiki_setup_downloading_mediaWiki_archive

# # Unzipping the MediaWiki archive to /var/www/
# - name: Step 9 - Unzipping the MediaWiki archive to /var/www/
#   become: true
#   become_user: root
#   ansible.builtin.unarchive:
#     src: "{{ mediawiki_server.mediawiki_parent_path }}{{ mediawiki_server.mediawiki_archive_name }}"
#     dest: "{{ mediawiki_server.mediawiki_parent_path }}"
#     remote_src: yes
#   when: mediawiki_hosts.server1 in inventory_hostname
#   tags:
#     - mediawiki_setup_unzipping_mediaWiki_archive


# # Removing MediaWiki archive from /var/www/mediawiki.tar.gz
# - name: Step 10 - Removing MediaWiki archive from /var/www/mediawiki.tar.gz
#   become: true
#   become_user: root
#   ansible.builtin.file:
#     path: "{{ mediawiki_server.mediawiki_parent_path }}{{ mediawiki_server.mediawiki_archive_name }}"
#     state: absent
#   when: mediawiki_hosts.server1 in inventory_hostname
#   tags:
#     - mediawiki_setup_removing_mediaWiki_archive

# # Copying the LocalSettings.php file to /var/www/mediawiki with '0755' permissions
# - name: Step 11 - Copying the LocalSettings.php file to /var/www/mediawiki with '0755' permissions
#   become: true
#   become_user: root
#   copy:
#     src: "{{ playbook_dir }}/common_files/mediawiki_servers/LocalSettings.php"
#     dest: "{{ mediawiki_server.mediawiki_parent_path }}{{ mediawiki_server.mediawiki_folder_name }}/"
#     mode: '0755'
#   when: mediawiki_hosts.server1 in inventory_hostname
#   tags:
#     - mediawiki_setup_copying_localsettings_php_mediawiki_configuratiion_file


# # Restarting the Nginx service
# - name: Step 12 - Restarting the Nginx service
#   become: true
#   become_user: root
#   systemd:
#     name: nginx
#     state: restarted
#   when: mediawiki_hosts.server1 in inventory_hostname
#   tags:
#     - mediawiki_setup_restart_nginx_service







# # =============================================================
# # Block with MediaWiki Server-2 tasks (vm-4-mediawiki-server-2)
# # =============================================================

# # Adding secret variables
# - name: Step 13 - Adding secret variables
#   include_vars: "{{ playbook_dir }}/common_files/ansible_secrets.yaml"
#   when: mediawiki_hosts.server2 in inventory_hostname
#   tags:
#     - mediawiki_setup_adding_secret_variables

# # Installing the pip3 packages
# - name: Step 14 - Pip3 packages installing
#   become: true
#   ansible.builtin.pip:
#     name: "{{ item }}" 
#     state: latest
#   loop:
#     - "{{ pip3_packages_to_install }}"
#   when: mediawiki_hosts.server2 in inventory_hostname
#   tags:
#     - mediawiki_setup_install_pip3_packages


# # Creating the /scripts directory with '0755' permissions, where scripts for the dump will be stored
# # Owner: rwx (read, write, and execute)
# # Group: r-x (read and execute)
# # Others: r-x (read and execute)
# - name: Step 15 - Creating the /scripts directory with '0755' permissions
#   become: true
#   become_user: root
#   ansible.builtin.file:
#     path: /scripts 
#     state: directory
#     mode: '0755'
#   when: mediawiki_hosts.server2 in inventory_hostname
#   tags:
#     - mediawiki_setup_creating_scripts_directory

# # Creating the .env file in /scripts directory with '0740' permissions
# # Owner: rwx (read, write, and execute)
# # Group: r-- (read only)
# # Others: --- (no access)
# - name: Step 16 - Creating the .env file in /scripts directory with '0740' permissions
#   become: true
#   become_user: root
#   ansible.builtin.file:
#     path: "/scripts/.env"
#     state: touch
#     group: dbadmin
#     mode: '0740'
#   when: mediawiki_hosts.server2 in inventory_hostname
#   tags:
#     - mediawiki_setup_creating_env_file



# # Copying the remote_rsync_mediawiki.py script to ~/scripts with '0755' permissions
# # Owner: rwx (read, write, and execute)
# # Group: r-x (read and execute)
# # Others: r-x (read and execute)
# - name: Step 17 - Copying the remote_rsync_mediawiki.py script to ~/scripts with '0755' permissions
#   become: true
#   become_user: root
#   copy:
#     src: "{{ playbook_dir }}/common_files/mediawiki_servers/{{ remote_rsync_script_name }}"   
#     dest: /scripts/
#     mode: '0755'
#   when: mediawiki_hosts.server2 in inventory_hostname
#   tags:
#     - mediawiki_setup_copying_remote_rsync_mediawiki_py



# # Filling the .env file with data
# - name: Step 18 - Filling the .env file with data
#   become: true
#   become_user: root
#   blockinfile:
#     path: /scripts/.env
#     block: |
#       REMOTE_HOST={{ secret_vm_4_mediawiki_server_2.remote_host_ip }}
#       REMOTE_USER={{ secret_vm_4_mediawiki_server_2.remote_user }}
#       PRIVATE_KEY_PATH={{ server_2.private_key_ssh_path }}
#       MEDIAWIKI_REMOTE_HOST_PATH={{ mediawiki_server.mediawiki_parent_path }}{{ mediawiki_server.mediawiki_folder_name }}
#       MEDIAWIKI_DESTINATION_PATH={{ mediawiki_server.mediawiki_parent_path }}
#       NGINX_CONF_FILE={{ mediawiki_server.nginx_conf_name }}
#     marker: "# {mark} Ansible managed block for .env"
#   when: mediawiki_hosts.server2 in inventory_hostname
#   tags:
#     - mediawiki_setup_filling_env_data



# # Copying the private SSH key to ~/.ssh with '600' permissions
# # Owner: rw- (read, write)
# - name: Step 19 - Copying Private ssh-key to ~/.ssh with '600' permissions
#   become: true
#   become_user: root
#   copy:
#     src: "{{ playbook_dir }}/common_files/id_ed25519"
#     dest: ~/.ssh
#     mode: '600'
#   when: mediawiki_hosts.server2 in inventory_hostname    
#   tags:
#     - mediawiki_setup_copying_private_ssh_key


# # Copying the logrotate_remote_rsync_mediawiki file to /etc/logrotate.d/
# # Command for forcing logrotate to run: logrotate -f /etc/logrotate.conf
# - name: Step 20 - Copying the logrotate_remote_rsync_mediawiki file to /etc/logrotate.d/
#   become: true
#   become_user: root
#   copy:
#     src: "{{ playbook_dir }}/common_files/mediawiki_servers/logrotate_remote_rsync_mediawiki"
#     dest: /etc/logrotate.d/
#   when: mediawiki_hosts.server2 in inventory_hostname  
#   tags:
#     - mediawiki_setup_logrotate_remote_rsync_mediawiki
    
# # Starting and enabling the logrotate service
# - name: Step 21 - Starting and enabling the logrotate service
#   service:
#     name=logrotate
#     state=started 
#     enabled=yes
#   when: mediawiki_hosts.server2 in inventory_hostname  
#   tags:
#     - mediawiki_setup_start_enable_logrotate_service


# # Adding the execution of pgdump_standby_postgresql.py to the cron job scheduler
# # minute: '0' - run at the beginning of the hour
# # hour: '*/4' - run every 4 hours"

# - name: Step 22 - Adding the execution of remote_rsync_mediawiki.py to the cron job scheduler
#   become: true
#   become_user: root
#   ansible.builtin.cron:
#     name: "Run remote_rsync_mediawiki.py script"
#     minute: "0"
#     hour: "*/4"
#     job: "/usr/bin/python3 /scripts/remote_rsync_mediawiki.py >> /scripts/remote_rsync_mediawiki.py.log 2>&1"
#   notify: restart_cron
#   tags:
#     - mediawiki_setup_adding_execution_remote_rsync_mediawiki_py_cron_job_scheduler


